# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html

services:
  kernel.listener.onrequest:
    class: AppBundle\EventListener\RequestListener
    tags:
      - { name: kernel.event_listener, event: kernel.request, priority: 1024 }